spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:.;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
    driverClassName: org.h2.Driver
    username: sa
    password:
    hikari:
      auto-commit: false
  application:
    name: back
  profiles:
    active: dev
  output:
    ansi:
      enabled: always

  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
springdoc:
  default-produces-media-type: application/json;charset=UTF-8
logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE

app:
  admin-api-key: NfMHpCLukCZL34GrC/K95fekVdpqJ4dQp/HiwmnXK1w=