name: Auto Close Issue
on:
  pull_request:
    types:
      - closed

jobs:
  close-issue:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: read
    steps:
      - name: Close linked issue
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ github.event.pull_request.body }}
          comment: "Closed by pull request #${{ github.event.pull_request.number }}"
          close-reason: completed
