name: Auto Close Issue
on:
  pull_request:
    types:
      - closed

jobs:
  close-issue:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Extract issue number
        id: extract
        run: |
          echo "issue=$(echo '${{ github.event.pull_request.body }}' | grep -oE '#[0-9]+' | tr -d '#')" >> $GITHUB_OUTPUT

      - name: Close linked issue
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ steps.extract.outputs.issue }}
          comment: "Closed by pull request #${{ github.event.pull_request.number }}"
          close-reason: completed
